steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_ARTIFACT_REPO}:${SHORT_SHA}",
        "services/tracking-service/",
      ]
images: ["${_ARTIFACT_REPO}:${SHORT_SHA}"]

options:
  logging: CLOUD_LOGGING_ONLY
